sonar.projectKey=10pshine-cohort-9_cohort-9-mern-10704-muhammad
sonar.organization=10pshine-cohort-9

sonar.projectName=cohort-9-mern-10704-muhammad
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/tests,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8
