sonar.projectKey=Muhammad-Sajid-Rajput_cohort-9-mern-10704-muhammad
sonar.organization=muhammad-sajid-rajput

sonar.projectName=cohort-9-mern-10704-muhammad
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/tests,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,backend/src/tests/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**
sonar.test.inclusions=backend/src/tests/**/*.test.ts,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
