export const API_CONSTANTS = {
	BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1',
	AUTH: {
		SIGNUP: '/auth/signup',
		LOGIN: '/auth/signin',
		LOGOUT: '/auth/logout',
		VERIFY: (token: string) => `/auth/verify/${token}`,
		REFRESH: '/auth/refreshToken',
		FORGOT_PASSWORD: '/auth/forgotPassword',
		RESET_PASSWORD: (token: string) => `/auth/resetPassword/${token}`,
		ME: '/auth/me',
		DELETE_USER: '/auth/deleteUser',
	},
	FOLDERS: {
		BASE: '/folders',
		ALL: '/folders/all',
		TRASH: '/folders/trash',
		RESTORE_TRASH: (id: string) => `/folders/trash/${id}/restore`,
		PERMANENT_DELETE_TRASH: (id: string) => `/folders/trash/${id}`,
		BY_ID: (id: string) => `/folders/${id}`,
		NOTES: (folderId: string) => `/folders/${folderId}/notes`,
		REMOVE_NOTE: (folderId: string, noteId: string) => `/folders/${folderId}/notes/${noteId}`,
	},
	NOTES: {
		BASE: '/notes',
		BY_ID: (id: string) => `/notes/${id}`,
		CHAT: '/notes/chat',
		TRASH: '/notes/trash',
		RESTORE: (id: string) => `/notes/trash/${id}/restore`,
		PERMANENT_DELETE: (id: string) => `/notes/trash/${id}`,
		EMPTY_TRASH: '/notes/trash',
	},
} as const;
