import { Note } from '../types/api.types';
import jsPDF from 'jspdf';

export const stripHtml = (html: string): string => {
  if (!html) return '';
  const div = document.createElement('div');
  div.innerHTML = html;
  return div.textContent || div.innerText || '';
};

export const formatNoteAsTxt = (note: Note): string => {
  const title = note.title.trim();
  const date = note.createdAt ? new Date(note.createdAt).toLocaleDateString() : '';
  const tags = note.tags && note.tags.length > 0 ? note.tags.join(', ') : 'None';
  const rawBody = note.content || note.body || '';
  const plainBody = stripHtml(rawBody).trim();

  return [
    '=================================================================',
    `TITLE: ${title}`,
    date ? `DATE: ${date}` : '',
    `TAGS: ${tags}`,
    '=================================================================',
    '',
    plainBody,
    '',
    '-----------------------------------------------------------------',
    'Generated by NotesApp',
  ]
    .filter((_, index) => index !== 2 || date !== '')
    .join('\n');
};

export const downloadTxtFile = (content: string, filename: string): void => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadPdfFile = (doc: jsPDF, filename: string): void => {
  doc.save(filename);
};

interface PdfContext {
  doc: jsPDF;
  pageWidth: number;
  pageHeight: number;
  margin: number;
  contentWidth: number;
  yOffset: number;
  renderWrappedText: (lines: string[], lineHeight: number, indent?: number, paragraphSpacing?: number) => void;
}

const renderPdfHeading = (ctx: PdfContext, tag: string, text: string) => {
  const { doc, contentWidth, margin, renderWrappedText } = ctx;
  if (tag === 'h1') {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(20, 20, 20);
    renderWrappedText(doc.splitTextToSize(text, contentWidth), 6, margin, 4);
  } else if (tag === 'h2') {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    renderWrappedText(doc.splitTextToSize(text, contentWidth), 5.5, margin, 3);
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    renderWrappedText(doc.splitTextToSize(text, contentWidth), 5, margin, 2);
  }
};

const renderPdfList = (ctx: PdfContext, tag: string, el: Element) => {
  const { doc, contentWidth, margin, renderWrappedText } = ctx;
  const items = Array.from(el.children);
  items.forEach((item, idx) => {
    const itemText = item.textContent?.trim() || '';
    if (!itemText) return;
    const prefix = tag === 'ol' ? `${idx + 1}. ` : '•  ';
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 40);
    renderWrappedText(doc.splitTextToSize(`${prefix}${itemText}`, contentWidth - 6), 5, margin + 4, 2);
  });
  ctx.yOffset += 3;
};

const renderPdfBlockquote = (ctx: PdfContext, text: string) => {
  const { doc, contentWidth, margin, pageHeight } = ctx;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const wrapped = doc.splitTextToSize(text, contentWidth - 10);
  for (const line of wrapped) {
    if (ctx.yOffset + 5 > pageHeight - margin) {
      doc.addPage();
      ctx.yOffset = 20;
    }
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(1.5);
    doc.line(margin, ctx.yOffset - 1, margin, ctx.yOffset + 4);
    doc.text(line, margin + 6, ctx.yOffset);
    ctx.yOffset += 5;
  }
  ctx.yOffset += 5;
};

export const generateNotePdf = (note: Note): jsPDF => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yOffset = 25;

  const renderWrappedText = (
    lines: string[],
    lineHeight: number,
    indent = margin,
    paragraphSpacing = 3
  ) => {
    for (const line of lines) {
      if (yOffset + lineHeight > pageHeight - margin) {
        doc.addPage();
        yOffset = 20;
      }
      doc.text(line, indent, yOffset);
      yOffset += lineHeight;
    }
    yOffset += paragraphSpacing;
  };

  // Header Banner
  doc.setFillColor(30, 41, 59);
  doc.rect(margin, yOffset - 5, contentWidth, 2, 'F');
  yOffset += 6;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  const titleLines = doc.splitTextToSize(note.title, contentWidth);
  renderWrappedText(titleLines, 8, margin, 4);

  // Metadata Line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const dateStr = note.createdAt ? new Date(note.createdAt).toLocaleDateString() : 'Unspecified';
  const tagsStr = note.tags && note.tags.length > 0 ? note.tags.join(', ') : 'None';
  doc.text(`Created: ${dateStr}   |   Tags: ${tagsStr}`, margin, yOffset);
  yOffset += 6;

  // Subtle separator line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, yOffset, pageWidth - margin, yOffset);
  yOffset += 8;

  // Content rendering
  const rawHtml = note.content || note.body || '';
  const parser = new DOMParser();
  const domDoc = parser.parseFromString(rawHtml, 'text/html');
  const elements = Array.from(domDoc.body.children);

  const ctx: PdfContext = {
    doc,
    pageWidth,
    pageHeight,
    margin,
    contentWidth,
    yOffset,
    renderWrappedText,
  };

  if (elements.length === 0) {
    const fallbackText = stripHtml(rawHtml);
    const paragraphs = fallbackText.split('\n');
    paragraphs.forEach((p) => {
      const trimmed = p.trim();
      if (!trimmed) {
        ctx.yOffset += 4;
        return;
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      renderWrappedText(doc.splitTextToSize(trimmed, contentWidth), 5, margin, 3);
    });
    return doc;
  }

  elements.forEach((el) => {
    const tag = el.tagName.toLowerCase();
    const text = el.textContent?.trim() || '';
    if (!text && tag !== 'hr') return;

    if (tag.startsWith('h')) {
      renderPdfHeading(ctx, tag, text);
    } else if (tag === 'hr') {
      if (ctx.yOffset + 8 > pageHeight - margin) {
        doc.addPage();
        ctx.yOffset = 20;
      }
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.5);
      doc.line(margin, ctx.yOffset, pageWidth - margin, ctx.yOffset);
      ctx.yOffset += 6;
    } else if (tag === 'ul' || tag === 'ol') {
      renderPdfList(ctx, tag, el);
    } else if (tag === 'blockquote') {
      renderPdfBlockquote(ctx, text);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      renderWrappedText(doc.splitTextToSize(text, contentWidth), 5, margin, 3);
    }
  });

  return doc;
};

// Export backward-compatible aliases
export const formatSingleNoteText = formatNoteAsTxt;
export const renderNoteToPdf = (_doc: jsPDF, note: Note): jsPDF => generateNotePdf(note);
